name: Snyk CI/CD Demo

on:
  push:
    branches: ["dev"]        # Runs whenever code is pushed directly to main
  pull_request:
    branches: ["main"]        # Runs whenever a PR is opened/updated targeting main

jobs:
  security:                   
    runs-on: ubuntu-latest     

    # Environment variables available to every step in this job
    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}         
    steps:
      # Step 1: Pull the repo's code onto the runner so later steps can access it
      - uses: actions/checkout@v5

      # Step 2: Install Node.js
      - name: Set up Node
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      # Step 3: Install the project's own dependencies (package.json)
      - name: Install dependencies
        run: npm install

      # Install the Snyk CLI globally so `snyk` commands work in later steps
      - name: Install Snyk CLI
        run: npm install -g snyk
      
      # SCAN scan
      # `|| true` means this step will NEVER fail the pipeline, even if issues are found
      #- name: Snyk SCA
        #run: snyk test || true

      # SCA Scan fail build if High or Critical severity issues are found, then it will fail
      - name: Snyk test failing pipeline
        run: snyk test --project-name=package.json --org=${{ vars.SNYK_ORG }} --severity-threshold=high

      # SCA Monitor
      - name: Snyk Open Source monitor
        run: snyk monitor
             --project-name=demoapp 
             --remote-repo-url=github.com/mawidors/Demo
             --target-reference=${{ github.ref_name }}

      # SAST scan
      - name: Snyk Code
        continue-on-error: true
        run: snyk code test --severity-threshold=high

      # SAST Snapshot
      - name: Snyk Code Snapshot Results
        continue-on-error: true
        run: snyk code test --severity-threshold=high --report 
             --project-name=demoapp 
             --remote-repo-url=github.com/mawidors/Demo
             --target-reference=${{ github.ref_name }}
      
